---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(data.table)
```

```{r}
mydata = read.csv(paste0(here::here(),"/../datos_1_intermedios/2020/comp/exportacion_EG2020_actual.csv"),colClasses = "character")

mydata = mydata %>%
  dplyr::filter(CANDIDATURA == "PRESIDENTE")%>%
  mutate_at(vars(!one_of("ID_MESA")),.funs = as.numeric)%>%
  mutate(vv = get_perc(VV,HAB))%>%
  mutate_at(c("BL","NU","MAS","CC","CREEMOS","FPV","PAN_BOL"), 
            .funs = list(perc = ~ get_perc(., VV)))

```
```{r}
mydata_2 = mydata %>%
  dplyr::select(HAB,VV,MAS, CC, CREEMOS,FPV, PAN_BOL)%>%
  gather(key="party", value = "valid_votes", 3:7)%>%
  dplyr::group_by(party)%>%
  dplyr::summarise(valid_votes = sum(valid_votes))

ggplot(data=mydata_2, aes(x=party, y = valid_votes))+
  geom_col()+
  labs(subtitle = paste0("Total valid votes: ", sum(mydata_2$valid_votes)))
```
```{r fig.width = 10}
mydata_3 = mydata %>%
  dplyr::select(contains("perc"))%>%
  dplyr::summarise_all(mean)%>%
  dplyr::mutate(MASmCC = MAS_perc - CC_perc)%>%
  gather(key="what", value = "percentage")

ggplot(mydata_3, aes(x=what, y=percentage))+
  geom_col()+
  scale_y_continuous(breaks=seq(-100,100,10))

```

